### ISSUE TITLE
Check wheel quality?

### ISSUE THREAD

**Issue by cdeil** [astropy/wheel-forge#2]
Is there a way to check if the wheels I get with `get_wheels.py` are OK?

As far as I know, once uploaded to PyPI, they can't be removed or replaced, so one should make sure they are OK before.

Maybe you run auto-checks for the wheels in CI already?
Can I see the logs from these checks somewhere?

**Comment by astrofrog** [comment]
We already run all the tests for the wheels - you can see the builds at

https://dev.azure.com/astropy-project/wheel-forge/_build

and the tests are run inside the 'Running autowheel' task. Maybe there is a way we could include the log from each build alongside each wheen when running ``get_wheels.py``, to make it easier to check/audit.

**Comment by cdeil** [comment]
This is what I see:
![Screenshot 2019-06-17 at 13 46 31](https://user-images.githubusercontent.com/852409/59602149-57c6fa00-9106-11e9-9055-b5823bca7218.png)


I think there's no mention of "autowheel", maybe that's something only you can see?
Change visibility to public?

**Comment by astrofrog** [comment]
Click on the first build in the list (the one with the green tick on the right), then select the build you want to check.
