### ISSUE TITLE
What wheels are available?

### ISSUE THREAD

**Issue by cdeil** [astropy/wheel-forge#4]
Is there a (public?) URL where one can see which wheels are available?

The README includes a link to https://dev.azure.com/astropy-project/wheel-forge/_build?definitionId=1 but I can't find that info there.

**Comment by astrofrog** [comment]
Not yet, because of the way Azure artifacts work. But you can run ``get_wheels.py`` to download all the available wheels for a given build locally for now. I agree it would be good to have a public feed in future, which is something I know is on the Azure roadmap.
