### ISSUE TITLE
Rethink repository organization and process

### ISSUE THREAD

**Issue by astrofrog** [astropy/wheel-forge#5]
I originally designed this repository so that the CI would run and build any wheels missing from PyPI, and maybe even eventually auto-upload them. The autowheel package will basically chekc for any version more recent than what's in ``autowheel.yml`` so that we don't need to update the repository when new releases are made. The flip side is that if this was run as a daily cron job, one would have to wait 24 hours to get wheels, or trigger builds manually.

However, this might be a bit too magic, and I'm now wondering whether it would make more sense to have a model similar to conda forge, where we have a mini yml recipe (which would really just look like a single section of the ``autowheel.yml`` file) for each package, and then either have one package per repo, or (to keep things easier to manage) maybe one package per branch in the repository. Then building a new version would require a PR to update the version number but could be done easily. Having one package per branch also means that we really only ever build what's needed.

@bsipocz @cdeil @larrybradley - any thoughts about this? No strong opinion is a valid thought :)

**Comment by bsipocz** [comment]
I like the one package per repo setup of conda-forge a lot. But here it seems a bit of an over-reaction. 

I don't necessarily like the one package per branch option, don't see how it would work efficiently without the logic of having one canonical main branch, but I suppose I can be convinced that it would work.

Also, having a daily cron sounds good, I don't think any of the releases has to be rushed out quicker, if they need to then a manual update is always an option.

**Comment by bsipocz** [comment]
What I would like to see, but haven't yet opened an issue for it, is that wheel-forge be able to pick up releases from github tags. e.g. being able to check on the wheel building before pushing a release. I think it's a blocker for the core wheels production being moved over here.

**Comment by astrofrog** [comment]
I am closing this as we now build wheels in the CI for each package, and am archiving this repo.
